-- View: public.mvw_eventofferdetails_nz

-- DROP MATERIALIZED VIEW IF EXISTS public.mvw_eventofferdetails_nz;

CREATE MATERIALIZED VIEW public.mvw_eventofferdetails_nz
TABLESPACE pg_default
AS
 SELECT "tblEVENTOFFERDTL_Legacy"."EVENTID",
    "tblEVENTOFFERDTL_Legacy"."PAGE",
    "tblEVENTOFFERDTL_Legacy"."OFFERNO",
    "tblEVENTOFFERDTL_Legacy"."PAGEPOSN",
    "tblEVENTOFFERDTL_Legacy"."OFFERID",
    "tblEVENTOFFERDTL_Legacy"."COMOFFERIC1",
    "tblEVENTOFFERDTL_Legacy"."SKU",
    "tblEVENTOFFERDTL_Legacy"."COUNTRY",
    "tblEVENTOFFERDTL_Legacy"."UOMCOPY",
    "tblEVENTOFFERDTL_Legacy"."SUBSKU",
    "tblEVENTOFFERDTL_Legacy"."LECOST",
    "tblEVENTOFFERDTL_Legacy"."FUTLEIND",
    "tblEVENTOFFERDTL_Legacy"."NATAVGCOST",
    "tblEVENTOFFERDTL_Legacy"."TLCOST",
    "tblEVENTOFFERDTL_Legacy"."CATCOST",
    "tblEVENTOFFERDTL_Legacy"."PURCHQTY",
    "tblEVENTOFFERDTL_Legacy"."OFFERQTY",
    "tblEVENTOFFERDTL_Legacy"."TIEUP",
    "tblEVENTOFFERDTL_Legacy"."ALLOCGROUP",
    "tblEVENTOFFERDTL_Legacy"."ALLOCTYPE",
    "tblEVENTOFFERDTL_Legacy"."GRP0QTY",
    "tblEVENTOFFERDTL_Legacy"."GRP1QTY",
    "tblEVENTOFFERDTL_Legacy"."GRP2QTY",
    "tblEVENTOFFERDTL_Legacy"."GRP3QTY",
    "tblEVENTOFFERDTL_Legacy"."GRP4QTY",
    "tblEVENTOFFERDTL_Legacy"."GRP5QTY",
    "tblEVENTOFFERDTL_Legacy"."TOTTIEUP",
    "tblEVENTOFFERDTL_Legacy"."TIEUPPCTFC",
    "tblEVENTOFFERDTL_Legacy"."CATFCST",
    "tblEVENTOFFERDTL_Legacy"."INCRFCST",
    "tblEVENTOFFERDTL_Legacy"."TIEUPCOST",
    "tblEVENTOFFERDTL_Legacy"."EDPRICE",
    "tblEVENTOFFERDTL_Legacy"."EDPRICEGST",
    "tblEVENTOFFERDTL_Legacy"."EDPRICEGSTSYS",
    "tblEVENTOFFERDTL_Legacy"."ADVPRICE",
    "tblEVENTOFFERDTL_Legacy"."ADVPRICEGST",
    "tblEVENTOFFERDTL_Legacy"."ADVPRICECALC",
    "tblEVENTOFFERDTL_Legacy"."FROMPRCIND",
    "tblEVENTOFFERDTL_Legacy"."GST",
    "tblEVENTOFFERDTL_Legacy"."EDUNITS",
    "tblEVENTOFFERDTL_Legacy"."EDEXTUNITCST",
    "tblEVENTOFFERDTL_Legacy"."EDEXTUNITSAL",
    "tblEVENTOFFERDTL_Legacy"."EXTADVPRICE",
    "tblEVENTOFFERDTL_Legacy"."CALCSAVEPCT",
    "tblEVENTOFFERDTL_Legacy"."CALCSAVEVAL",
    "tblEVENTOFFERDTL_Legacy"."EDTM$",
    "tblEVENTOFFERDTL_Legacy"."EDTM%",
    "tblEVENTOFFERDTL_Legacy"."FCSTCOST",
    "tblEVENTOFFERDTL_Legacy"."FCSTSALES",
    "tblEVENTOFFERDTL_Legacy"."FCSTTM$",
    "tblEVENTOFFERDTL_Legacy"."FCSTTM%",
    "tblEVENTOFFERDTL_Legacy"."ADVTM$",
    "tblEVENTOFFERDTL_Legacy"."GROSSMAR",
    "tblEVENTOFFERDTL_Legacy"."GROSSMAR%",
    "tblEVENTOFFERDTL_Legacy"."MANEXPORT",
    "tblEVENTOFFERDTL_Legacy"."MANEXPORTDTE",
    "tblEVENTOFFERDTL_Legacy"."MANEXPORTUSERID",
    "tblEVENTOFFERDTL_Legacy"."MANEXPORTHYBDTE",
    "tblEVENTOFFERDTL_Legacy"."HYBPROMCDE",
    "tblEVENTOFFERDTL_Legacy"."HYBPROMCDEPREV",
    "tblEVENTOFFERDTL_Legacy"."EXPSEQNUM",
    "tblEVENTOFFERDTL_Legacy"."PRCONLY",
    "tblEVENTOFFERDTL_Legacy"."PARTNO",
    "tblEVENTOFFERDTL_Legacy"."SRMIND",
    "tblEVENTOFFERDTL_Legacy"."SOH_STORE",
    "tblEVENTOFFERDTL_Legacy"."SOH_DC",
    "tblEVENTOFFERDTL_Legacy"."DESC",
    "tblEVENTOFFERDTL_Legacy"."FLWAEXCL",
    "tblEVENTOFFERDTL_Legacy"."optCatFcstLock",
    "tblEVENTOFFERDTL_Legacy"."CREATED",
    "tblEVENTOFFERDTL_Legacy"."USERID",
    "tblEVENTOFFERDTL_Legacy"."UPDATED",
    "tblEVENTOFFERDTL_Legacy"."InventoryReviewInd",
    "tblEVENTOFFERDTL_Legacy"."RAUCLRIND",
    "tblEVENTOFFERDTL_Legacy"."OM"
   FROM "tblEVENTOFFERDTL_Legacy"
     JOIN "tblEVENTHDR_Legacy" ON "tblEVENTOFFERDTL_Legacy"."EVENTID" = "tblEVENTHDR_Legacy"."EVENTID" AND "tblEVENTOFFERDTL_Legacy"."COUNTRY"::text = "tblEVENTHDR_Legacy"."COUNTRY"::text
  WHERE "tblEVENTOFFERDTL_Legacy"."COUNTRY"::text = 'NZ'::text AND "tblEVENTHDR_Legacy"."STARTDTE" >= '2022-01-01'::date AND ("tblEVENTOFFERDTL_Legacy"."PAGEPOSN" <> 0 AND upper("tblEVENTHDR_Legacy"."EVENTTYPE"::text) = 'RETAIL CATALOGUE'::text OR upper("tblEVENTHDR_Legacy"."EVENTTYPE"::text) <> 'RETAIL CATALOGUE'::text)
UNION ALL
 SELECT "tEventOfferDetail"."eventId" AS "EVENTID",
    "tEventOfferDetail".page AS "PAGE",
    "tEventOfferDetail"."offerNo" AS "OFFERNO",
        CASE
            WHEN "tEventOfferDetail"."pagePosition" = 0 THEN "tEventOfferDetail"."offerId"
            ELSE "tEventOfferDetail"."pagePosition"
        END AS "PAGEPOSN",
    "tEventOfferDetail"."offerId" AS "OFFERID",
    "tEventOfferDetail"."comOfferCategory1" AS "COMOFFERIC1",
    "tEventOfferDetail".sku AS "SKU",
    "tEventOfferDetail".country AS "COUNTRY",
    "tEventOfferDetail"."unitOfMeasureCopy" AS "UOMCOPY",
    "tEventOfferDetail"."substituteSku" AS "SUBSKU",
    "tEventOfferDetail"."LatestEffectiveCost" AS "LECOST",
    NULL::boolean AS "FUTLEIND",
    "tEventOfferDetail"."nationalAverageCost" AS "NATAVGCOST",
    "tEventOfferDetail"."trueLandedCost" AS "TLCOST",
    "tEventOfferDetail"."categoryCost" AS "CATCOST",
    "tEventOfferDetail"."purchaseQuantity" AS "PURCHQTY",
    "tEventOfferDetail"."offerQuantity" AS "OFFERQTY",
        CASE
            WHEN "tEventOffer"."offLocation" = 'Y'::text THEN 'Location'::text
            ELSE ''::text
        END AS "TIEUP",
    "tEventOfferDetail"."allocationGroup" AS "ALLOCGROUP",
    "tEventOfferDetail"."allocationType" AS "ALLOCTYPE",
    "tEventOfferDetail"."group0Quantity" AS "GRP0QTY",
    "tEventOfferDetail"."group1Quantity" AS "GRP1QTY",
    "tEventOfferDetail"."group2Quantity" AS "GRP2QTY",
    "tEventOfferDetail"."group3Quantity" AS "GRP3QTY",
    "tEventOfferDetail"."group4Quantity" AS "GRP4QTY",
    "tEventOfferDetail"."group5Quantity" AS "GRP5QTY",
    "tEventOfferDetail"."totalTieUp" AS "TOTTIEUP",
    NULL::numeric AS "TIEUPPCTFC",
    "tEventOfferDetail".categoryforecast AS "CATFCST",
    "tEventOfferDetail"."incrementalForecast" AS "INCRFCST",
    "tEventOfferDetail"."tieUpCost" AS "TIEUPCOST",
    "tEventOfferDetail"."everydayPrice" AS "EDPRICE",
    "tEventOfferDetail"."everydayPriceGst" AS "EDPRICEGST",
    "tEventOfferDetail"."everydayPriceGstSys" AS "EDPRICEGSTSYS",
    "tEventOfferDetail"."advertisedPrice" AS "ADVPRICE",
    "tEventOfferDetail"."advertisedPriceGst" AS "ADVPRICEGST",
    "tEventOfferDetail"."advertisedPriceCalculated" AS "ADVPRICECALC",
    "tEventOfferDetail"."fromPriceIndicator" AS "FROMPRCIND",
    "tEventOfferDetail".gst AS "GST",
    "tEventOfferDetail"."everydayUnits" AS "EDUNITS",
    "tEventOfferDetail"."everydayExtendedUnitCost" AS "EDEXTUNITCST",
    "tEventOfferDetail"."everydayExtendedUnitSales" AS "EDEXTUNITSAL",
    "tEventOfferDetail"."extendedAdvertisedPrice" AS "EXTADVPRICE",
    "tEventOfferDetail"."calculatedSavePercentage" / 100::numeric AS "CALCSAVEPCT",
    "tEventOfferDetail"."calculatedSaveValue" AS "CALCSAVEVAL",
    "tEventOfferDetail"."everydayTradeMargin$" AS "EDTM$",
    "tEventOfferDetail"."everydayTradeMargin%" / 100::numeric AS "EDTM%",
    "tEventOfferDetail"."forecastCost" AS "FCSTCOST",
    "tEventOfferDetail"."forecastSales" AS "FCSTSALES",
    "tEventOfferDetail"."forecastTradeMargin$" AS "FCSTTM$",
    "tEventOfferDetail"."forecastTradeMargin%" / 100::numeric AS "FCSTTM%",
    "tEventOfferDetail"."advertisedTradeMargin$" AS "ADVTM$",
    "tEventOfferDetail"."grossMargin" AS "GROSSMAR",
    "tEventOfferDetail"."grossMargin%" / 100::numeric AS "GROSSMAR%",
    NULL::boolean AS "MANEXPORT",
    NULL::date AS "MANEXPORTDTE",
    NULL::character varying AS "MANEXPORTUSERID",
    NULL::date AS "MANEXPORTHYBDTE",
    "tEventOfferDetail"."hybrisPromoCode" AS "HYBPROMCDE",
    "tEventOfferDetail"."hybrisPromoCodePrevious" AS "HYBPROMCDEPREV",
    NULL::integer AS "EXPSEQNUM",
    "tEventOfferDetail"."priceOnly" AS "PRCONLY",
    "tEventOfferDetail"."partNo" AS "PARTNO",
    "tEventOfferDetail"."showroomIndicator" AS "SRMIND",
    "tEventOfferDetail"."stockOnHandStore" AS "SOH_STORE",
    "tEventOfferDetail"."stockOnHandDC" AS "SOH_DC",
    "tEventOfferDetail".description AS "DESC",
    false AS "FLWAEXCL",
    NULL::boolean AS "optCatFcstLock",
    "tEventOfferDetail".created AS "CREATED",
    "tEventOfferDetail"."userID" AS "USERID",
    "tEventOfferDetail".updated AS "UPDATED",
    "tEventOfferDetail"."inventoryReviewIndicator" AS "InventoryReviewInd",
    "tEventOfferDetail"."clearanceIndicator" AS "RAUCLRIND",
    NULL::numeric AS "OM"
   FROM "tEventOfferDetail"
     JOIN "tEventOffer" ON "tEventOffer"."offerId" = "tEventOfferDetail"."offerId" AND "tEventOffer"."offerNumber" = "tEventOfferDetail"."offerNo" AND "tEventOffer"."isOfferActive" = true
     JOIN "tEvent" ON "tEvent"."eventId" = "tEventOfferDetail"."eventId" AND "tEvent".country::text = "tEventOfferDetail".country::text
  WHERE (upper("tEvent".status::text) IN ('OPEN'::text, 'LOCKED'::text) AND "tEventOfferDetail"."isSkuActive" = true OR upper("tEvent".status::text) IN('COMPLETED'::text, 'CANCELLED'::text)) AND "tEventOfferDetail".country::text = 'NZ'::text AND upper("tEvent".status::text) <> 'CANCELLED'::text AND ("tEventOfferDetail"."pagePosition" <> 0 AND upper("tEvent"."eventType"::text) = 'RETAIL CATALOGUE'::text OR upper("tEvent"."eventType"::text) <> 'RETAIL CATALOGUE'::text)
WITH DATA;